notifications:
  email: false

dist: xenial
group: edge
sudo: true

matrix:
  include:
    - language: python
      python: "3.9"
      services:
        - docker
    - language: python
      python: "nightly"
      services:
        - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libldap2-dev libsasl2-dev ldap-utils sasl2-bin
  # For GSSAPI authentication.
  - sudo apt-get install -y krb5-user libsasl2-modules-gssapi-mit libkrb5-dev
  - sudo apt list --installed
  - pip install pipenv
  - export PIP_NO_BINARY=gevent  # Fix issues with gevent 1.3.5/greenlet 0.4.13 on Python 3.7
  - pipenv install --dev --skip-lock
  - pipenv install cffi
  - pipenv graph
  - mkdir /tmp/bonsai
  - sudo chown 2001:2000 /tmp/bonsai  # uid:gid for ldap group and user in container
  - docker build -t bonsai -f ./.ci/docker/Dockerfile .
  - docker run --cap-add=NET_ADMIN -v /tmp/bonsai/:/home/ldap/run/:z -d -h bonsai.test --name server bonsai
  # Set container IP in the hosts file.
  - DOCKER_IP=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' server`
  - sudo bash -c 'echo -e "\n'$DOCKER_IP'        bonsai.test" >> /etc/hosts'
  - cat /etc/hosts
  - ping -c 2 bonsai.test
  # Waiting for slapd to start in the container.
  - sleep 4
  # Check that everything is started.
  - docker exec server ps aux
  - docker exec server /bin/bash -c "cat /var/log/supervisord.log"
  # Check that slapd is working.
  - ldapwhoami -Y DIGEST-MD5 -h bonsai.test -U admin -w p@ssword
  - ldapsearch -h bonsai.test -b "" -s base 'objectclass=*' -x -LLL +
  - ldapsearch -VV
  - saslpluginviewer

install:
  - printf "\n\n[options]\nzip_safe = False" >> setup.cfg # Avoid zipped egg file, messes with coverage and pipenv.
  - export CFLAGS="-coverage"
  - pipenv run python setup.py install

before_script:
  # Change localhost IP in test.ini to the container's.
  - sed -i.bak "s/127.0.0.1/$DOCKER_IP/g" ./tests/test.ini
  # Set used Kerberos config file to my own.
  - export KRB5_CONFIG="$TRAVIS_BUILD_DIR/.ci/krb5/krb5.conf"
  # Set install path for coverage.py.
  - INSTALL_PATH=`pipenv run python -c "import bonsai; print(bonsai.__file__[:-12])"`
  - echo $INSTALL_PATH

script:
  - pipenv run py.test -v --cov-config .coveragerc --cov-report= --cov=$INSTALL_PATH

after_success:
  # Change path of the Python source files in .coverage.
  - sed -i.bak 's|'$INSTALL_PATH'|'$TRAVIS_BUILD_DIR/src/bonsai'|g' .coverage
  - codecov

#after_failure:
  # Print out slapd log for debugging.
  #- docker exec server cat /var/log/slapd.log
